---
deployment:
      tasks:
        - export DEPLOYPATH=/home/bookentory/public_html
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp signin.css $DEPLOYPATH
        - /bin/cp * $DEPLOYPATH
